-- Migration: BRICS, Trade, & Critical Minerals Expansion (100+ Topics)
-- Run via: mysql -u user -p database < core/sql/migration_004_brics_trade_minerals.sql

INSERT INTO `topics` (`category`, `keyword`, `search_query`, `importance`) VALUES

-- BRICS & GLOBAL GOVERNANCE (2025-2026 Focus)
('Geopolitics', 'BRICS 2025 Summit Brazil', 'BRICS Summit 2025 Rio de Janeiro agenda', 10),
('Geopolitics', 'BRICS 2026 Summit India', 'BRICS Summit 2026 India theme objectives', 10),
('Economics', 'BRICS Pay System', 'BRICS Pay payment system launch adoption', 10),
('Economics', 'BRICS Currency Unit', 'BRICS common currency unit proposal', 9),
('Economics', 'BRICS Grain Exchange', 'BRICS grain exchange agricultural trade', 8),
('Economics', 'New Development Bank Bonds', 'New Development Bank local currency bonds', 8),
('Geopolitics', 'BRICS Partner Country Model', 'BRICS partner country category criteria', 7),
('Geopolitics', 'Turkey BRICS Membership', 'Turkey BRICS application status', 8),
('Geopolitics', 'Thailand BRICS Membership', 'Thailand BRICS alliance participation', 7),
('Geopolitics', 'Malaysia BRICS Membership', 'Malaysia joining BRICS economic impact', 7),
('Geopolitics', 'Indonesia BRICS Application', 'Indonesia BRICS membership decision', 8),
('Economics', 'De-dollarization Strategy', 'BRICS de-dollarization strategies 2025', 9),
('Economics', 'BRICS Interbank Cooperation', 'BRICS interbank cooperation mechanism', 7),
('Technology', 'BRICS Satellite Constellation', 'BRICS remote sensing satellite constellation data', 7),
('Technology', 'BRICS AI Study Group', 'BRICS AI study group governance standards', 8),
('Economics', 'BRICS Digital Economy', 'BRICS digital economy partnership agreement', 7),
('Economics', 'Local Currency Settlement', 'China trade local currency settlement RMB', 9),
('Economics', 'BRICS Cross-Border Payments', 'BRICS cross-border payment interoperability', 9),
('Geopolitics', 'China-Brazil Strategic Partnership', 'China-Brazil comprehensive strategic partnership 2025', 8),
('Geopolitics', 'China-India BRICS Relations', 'China-India relations post-border deal BRICS', 9),
('Geopolitics', 'China Global South Leadership', 'China leadership Global South development', 8),
('Geopolitics', 'China-Arab States Cooperation', 'China-Arab States Summit outcomes trade', 8),
('Geopolitics', 'China-Pacific Island Countries', 'China Pacific Island countries cooperation', 7),

-- REGIONAL TRADE & CORRIDORS
('Economics', 'China-ASEAN FTA 3.0', 'China-ASEAN Free Trade Area 3.0 upgrade', 10),
('Economics', 'INSTC Trade Route', 'International North-South Transport Corridor China role', 9),
('Economics', 'Middle Corridor Trade', 'Trans-Caspian International Transport Route China Europe', 9),
('Economics', 'China-Central Asia Corridor', 'China-Central Asia-West Asia Economic Corridor', 8),
('Geopolitics', 'CPEC Phase 2', 'China-Pakistan Economic Corridor Phase 2 projects', 9),
('Economics', 'New International Land-Sea Corridor', 'New International Land-Sea Trade Corridor expansion', 8),
('Economics', 'China-Europe Railway Express', 'China-Europe Railway Express volume 2025', 8),
('Economics', 'Chancay Port Logistics', 'China-Peru Chancay Port logistics hub impact', 10),
('Economics', 'China-Africa Trade Expo', 'China-Africa Economic and Trade Expo deals', 7),
('Geopolitics', 'FOCAC Outcomes 2025', 'Forum on China-Africa Cooperation action plan 2025', 9),
('Economics', 'China-GCC FTA', 'China-GCC Free Trade Agreement negotiations status', 8),
('Economics', 'China-Nicaragua FTA', 'China-Nicaragua Free Trade Agreement benefits', 6),
('Economics', 'China-Ecuador FTA', 'China-Ecuador Free Trade Agreement exports', 6),
('Economics', 'China-Serbia FTA', 'China-Serbia Free Trade Agreement implementation', 7),
('Technology', 'Digital Silk Road 2026', 'Digital Silk Road 5G optic cables export', 8),
('Social', 'Health Silk Road', 'Health Silk Road medical cooperation', 6),
('Geopolitics', 'Polar Silk Road', 'Polar Silk Road Arctic shipping routes', 7),
('Economics', 'China-Singapore Connectivity', 'China-Singapore (Chongqing) Connectivity Initiative', 7),
('Economics', 'China-Vietnam Railway', 'China-Vietnam railway upgrade interconnection', 8),
('Economics', 'China-Laos Railway Trade', 'China-Laos Railway cross-border freight volume', 8),
('Economics', 'Jakarta-Bandung HSR Impact', 'Jakarta-Bandung High-Speed Railway economic impact', 8),
('Economics', 'ECRL Malaysia', 'East Coast Rail Link Malaysia progress', 7),
('Geopolitics', 'Gwadar Port Development', 'Gwadar Port operational capacity CPEC', 8),
('Geopolitics', 'Djibouti Logistics Base', 'China Djibouti support base activities', 7),
('Economics', 'Hambantota Port Industry', 'Hambantota Port industrial zone investment', 7),
('Economics', 'Piraeus Port Expansion', 'COSCO Piraeus Port expansion plans', 8),
('Economics', 'China-Kyrgyzstan-Uzbekistan Railway', 'China-Kyrgyzstan-Uzbekistan Railway construction', 9),
('Economics', 'Mongolia-China Coal Railway', 'Mongolia-China cross-border railway coal transport', 7),
('Economics', 'China-Russia Amur Bridge', 'China-Russia Amur River bridge trade flow', 7),
('Economics', 'Cross-Border E-commerce Zones', 'China cross-border e-commerce pilot zones comprehensive', 8),

-- CRITICAL MINERALS & RESOURCES
('Economics', 'Gallium Export Control', 'China gallium export control impact prices', 10),
('Economics', 'Germanium Supply Chain', 'China germanium export restrictions supply chain', 10),
('Economics', 'Antimony Export License', 'China antimony export licensing regulations', 9),
('Economics', 'Tungsten Export Quota', 'China tungsten export quota mining control', 9),
('Technology', 'Rare Earth Processing Ban', 'China rare earth processing technology export ban', 10),
('Economics', 'Heavy Rare Earths Supply', 'China heavy rare earth elements supply shortage', 9),
('Economics', 'Light Rare Earths Quota', 'China light rare earth production quota 2025', 8),
('Economics', 'Lithium Refining Dominance', 'China lithium refining capacity global share', 9),
('Economics', 'Cobalt Processing Market', 'China cobalt processing market share DRC', 8),
('Economics', 'Graphite Export Restrictions', 'China graphite export controls battery anode', 9),
('Economics', 'Magnesium Supply Chain', 'China magnesium production Europe reliance', 8),
('Economics', 'Titanium Sponge Production', 'China titanium sponge industry aerospace', 7),
('Economics', 'Vanadium Battery Market', 'China vanadium redox flow battery market', 7),
('Economics', 'Indium Strategic Reserve', 'China indium production strategic reserve', 7),
('Economics', 'Bismuth Export Data', 'China bismuth export statistics prices', 6),
('Economics', 'Tellurium Usage Solar', 'China tellurium demand cadmium telluride solar', 6),
('Economics', 'Molybdenum Supply', 'China molybdenum supply steel prices', 7),
('Technology', 'Deep Sea Mining ISA', 'China deep sea mining licenses International Seabed Authority', 8),
('Economics', 'Mineral Recycling Industry', 'China critical mineral recycling EV batteries', 7),
('Economics', 'Mining Investment Africa', 'China mining investment Africa lithium cobalt', 8),
('Economics', 'Lithium Mining Latin America', 'China lithium investment Latin America Chile Bolivia', 8),
('Economics', 'Nickel Mining Indonesia', 'China nickel smelter investment Indonesia', 9),
('Economics', 'Copper Mining DRC', 'China copper mining DRC infrastructure for minerals', 8),
('Economics', 'Iron Ore Diversification', 'China iron ore import diversification Simandou', 9),
('Economics', 'Bauxite Reliance Guinea', 'China bauxite imports Guinea supply chain', 7),

-- TECHNOLOGY & ADVANCED INDUSTRY
('Technology', 'Solid-State Battery 2026', 'China solid-state battery mass production timeline', 10),
('Technology', 'Sodium-Ion Battery', 'China sodium-ion battery commercialization CATL', 8),
('Technology', 'Hydrogen Heavy Trucks', 'China hydrogen fuel cell heavy truck adoption', 7),
('Economics', 'Commercial Aerospace Industry', 'China commercial aerospace industry development', 8),
('Economics', 'Low-Altitude Economy', 'China low-altitude economy eVTOL drone logistics', 9),
('Technology', 'Humanoid Robot Standards', 'China humanoid robot industry standards roadmap', 8),
('Technology', 'Brain-Computer Interface', 'China brain-computer interface technology Neuralink rival', 8),
('Technology', '6G R&D Progress', 'China 6G technology research development progress', 9),
('Technology', 'Third-Gen Semiconductors', 'China third-generation semiconductor SiC GaN', 9),
('Economics', 'Solar Overcapacity', 'China photovoltaic supply chain overcapacity consolidation', 8),
('Economics', 'Wind Turbine Exports', 'China wind turbine export prices competition', 7),
('Economics', 'EV Export Tariffs', 'China EV export tariffs EU US trade defense', 10),
('Politics', 'Data Security Law', 'China Data Security Law cross-border data transfer', 9),
('Technology', 'Generative AI Regulation', 'China Generative AI Interim Measures enforcement', 9),
('Technology', 'Computing Power Network', 'China East-West Computing Resource Transfer project', 8),

-- FINANCE & MACROECONOMICS
('Economics', 'Swap Connect', 'China Swap Connect interest rate derivatives', 7),
('Social', 'Northbound Travel', 'Northbound Travel for Hong Kong Vehicles policy', 6),
('Economics', 'QFII Expansion', 'China QFII rule changes foreign investment', 7),
('Economics', 'Wealth Management Connect', 'Cross-boundary Wealth Management Connect GBA', 7),
('Economics', 'CIC Investment Strategy', 'China Investment Corporation sovereign wealth fund strategy', 8),
('Economics', 'Forex Reserves 2025', 'China foreign exchange reserves composition gold', 8),
('Economics', 'PBOC Gold Reserves', 'PBOC gold reserves accumulation trend', 9),
('Technology', 'Digital Yuan Cross-Border', 'Digital Yuan cross-border pilot mBridge', 9),
('Economics', 'CIPS Growth', 'CIPS transaction volume growth SWIFT alternative', 9),
('Economics', 'RMB Internationalization', 'RMB internationalization trade settlement share', 9);
